# Generated by Django 4.2.10 on 2026-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('activity', models.CharField(max_length=50)),
                ('hydration', models.BooleanField(default=False)),
                ('sleep', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('habits', models.BooleanField(default=False)),
            ],
        ),
    ]
